### ISSUE TITLE
GQL is executed before useRoute

### ISSUE THREAD

**Issue by ririen** [Diizzayy/nuxt-graphql-client#33]
After recent Nuxt updates, GQL functions with dynamic route stopped working for me.

I created a reproduction that takes the `limit` parameter from `useRoute().fullPath` and switching between pages returns the data as `null`.

CodeSandbox does not return an error in the console for some reason.

The GQL function seems to be executing before `useRoute()` is executed

I'm not sure if I made a good reproduction, but locally the project just stopped working returning `undefined` when I add anything from route to the GQL parameter.

Reproduction:
https://codesandbox.io/s/naughty-cherry-yyoelj

**Comment by Diizzayy** [comment]
@ririen This bug was caused by recent changes to Nuxt that caused the client side runtimeConfig to resolve incorrectly. It should be fixed now that nuxt/framework#4267 is merged.

Also, I had a look at your reproduction and just a few points to make note of:

- when using `useAsyncData` on dynamic pages you have to ensure that the `key` is unique per page. Using an already populated key will result in stale data across pages.

```diff
- const { data, error } = await useAsyncData("starlink", () =>
+ const { data, error } = await useAsyncData("starlink" + <PAGE_KEY>, () =>
  GqlLaunches({ limit: route.fullPath.replace("/", "") })
);
```

- The variable type for `limit` is supposed to be an Int, as opposed to string. So that would also cause the query to fail
```diff
- GqlLaunches({ limit: route.fullPath.replace("/", "") })
+ GqlLaunches({ limit: Number(route.fullPath.replace("/", "")) })
```
